version: '3'

services:
  redis:
    image: redis:4
    ports:
      - '16379:6379'
  rdb:
    image: mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - '13306:3306'
