<?php

declare(strict_types=1);

namespace Issei\SimpleJobQueue\Util;

use Doctrine\Instantiator\Instantiator;
use Issei\SimpleJobQueue\Job;
use Issei\SimpleJobQueue\JobId;
use Ramsey\Uuid\Uuid;

/**
 * Serializes a job instance into an array containing only primitive values,
 * it can also deserialize contrary.
 *
 * @internal
 *
 * @author Issei Murasawa <issei.m7@gmail.com>
 */
class JobSerializer
{
    /**
     * @var Instantiator
     */
    private $instantiator;

    /**
     * @var \ReflectionProperty
     */
    private $jobIdPropertyReflector;

    /**
     * @var \ReflectionProperty[]
     */
    private $jobPropertyReflectors;

    public function __construct(Instantiator $instantiator = null)
    {
        $this->instantiator = $instantiator ?: new Instantiator();
    }

    /**
     * Serializes the job instance into an array.
     *
     * @param Job $job
     *
     * @return array
     */
    public function serialize(Job $job): array
    {
        $this->ensureReflectorsInitialized();

        return [
            'id' => $job->getId()->__toString(),
            'name' => $this->jobPropertyReflectors['name']->getValue($job),
            'arguments' => \json_encode($this->jobPropertyReflectors['arguments']->getValue($job)),
            'max_retries' => $this->jobPropertyReflectors['maxRetries']->getValue($job),
            'retries' => $this->jobPropertyReflectors['retries']->getValue($job),
        ];
    }

    /**
     * Deserializes an array generated by this class into a job instance.
     *
     * @param array $serialized
     *
     * @return Job
     */
    public function deserialize(array $serialized): Job
    {
        $this->ensureReflectorsInitialized();

        $job = $this->instantiator->instantiate(Job::class);

        $arguments = \json_decode($serialized['arguments'], true);
        \assert(\is_array($arguments));

        $this->jobPropertyReflectors['id']->setValue($job, new JobId(Uuid::fromString($serialized['id'])));
        $this->jobPropertyReflectors['name']->setValue($job, $serialized['name']);
        $this->jobPropertyReflectors['arguments']->setValue($job, $arguments);
        $this->jobPropertyReflectors['maxRetries']->setValue($job, $serialized['max_retries']);
        $this->jobPropertyReflectors['retries']->setValue($job, $serialized['retries']);

        return $job;
    }

    private function ensureReflectorsInitialized(): void
    {
        if ($this->jobIdPropertyReflector) {
            return;
        }

        $jobIdRefl = new \ReflectionClass(JobId::class);
        $this->jobIdPropertyReflector = $jobIdRefl->getProperty('id');
        $this->jobIdPropertyReflector->setAccessible(true);

        $jobRefl = new \ReflectionClass(Job::class);
        foreach (['id', 'name', 'arguments', 'maxRetries', 'retries'] as $propName) {
            $this->jobPropertyReflectors[$propName] = $jobRefl->getProperty($propName);
            $this->jobPropertyReflectors[$propName]->setAccessible(true);
        }
    }
}
